# Generated by Django 2.0.7 on 2018-07-03 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('BUG', 'Bug Reports'), ('ACC_ISSUE', 'Account Issue'), ('F_REQ', 'Feature Requests'), ('O', 'Any other Request')], default='BUG', max_length=30)),
                ('issue', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tickets.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket_state', models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='PUB', max_length=10)),
                ('completion_state', models.CharField(choices=[('REC', 'Received'), ('WOR', 'Already working'), ('RES', 'Resolved'), ('N_POS', 'Not Possible')], default='REC', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
