# Generated by Django 2.0.7 on 2018-07-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180704_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completion_state',
            field=models.CharField(choices=[('Received', 'Received'), ('Already working', 'Already working'), ('Resolved', 'Resolved'), ('Not Possible', 'Not Possible')], default='Received', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tag',
            field=models.CharField(choices=[('Bug Reports', 'Bug Reports'), ('Account Issue', 'Account Issue'), ('Feature Request', 'Feature Request'), ('Any other Request', 'Any other Request')], default='Bug Reports', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_state',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10),
        ),
    ]
