# Generated by Django 2.0.7 on 2018-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180706_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='open_state',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
